# Generated by Django 5.0.3 on 2024-03-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('delivered', 'delivered'), ('prepared', 'prepared'), ('in delivery', 'in delivery')], default='prepared', max_length=30),
        ),
    ]
