# Generated by Django 5.0.3 on 2024-04-02 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_orderdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.orderdata'),
            preserve_default=False,
        ),
    ]
