# Generated by Django 5.0.3 on 2024-04-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_order_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='uuid',
            field=models.UUIDField(default=0),
            preserve_default=False,
        ),
    ]
